export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR";
export const ADDUSERDATA = "ADDUSERDATA";
export const ADDDEVICEINFO = "ADDDEVICEINFO";
export const UPDATE_DETAILS = "UPDATE_DETAILS";

export const CHANGE_ACTIVE_SIDEBAR = "CHANGE_ACTIVE_SIDEBAR";
export const TOGGLE_LOADER = "TOGGLE_LOADER";

export const LOGOUT = "LOGOUT";
